# Comment: config_871.yaml Configuration
details:
  team_members:
    team_leader   : "Maneesh Sutar"  
    team_member_1 : "Tanay Kejriwal"
    team_member_2 : "Prajwal Ahire"
    team_member_3 : "Sanket Mote"
  
  Information:
    team_id : "eYRC#871"
    college : "Walchand College of Engineering , sangli"
    address : "Vishrambag, Sangli"  
